required_arguments:
  parent_folder: /lustre/hawcz01/scratch/userspace/sgroetsch/PixiALPS/fresh_start_test_multi
  coord_1: 83.63
  coord_2: 22.01
  coordinate_system: C
  map_tree_file_path: /lustre/hawcz01/hawcroot/maps/pass-5.final/Pass5-Final-ML-Map/pass5f-fhit2pct-chunk0001-1510-ML/maptree-fhit2pct-pass5f-mlp-chunk1-1510.root
  detector_response_file_path: /lustre/hawcz01/hawcroot/maps/pass-5.final/Pass5-Final-ML-Map/pass5f-fhit2pct-chunk0001-1510-ML/detRes-fhit2pct-pass5f-mlp-refit.root
  bin_list: B0C0 B0C1 B1C0 B1C1 B2C0 B2C1 B3C0 B3C1 B4C0 B4C1 B5C0 B5C1 B6C0 B6C1 B7C0 B7C1 B8C0 B8C1 B9C0 B9C1 B10C0 B10C1
  estimator: p5_nhit
  fit_name: fresh_crab
  pixi_aerie_folder: /data/disk01/home/sgroetsch/aerie
  fitmodel_folder: /lustre/hawcz01/scratch/userspace/sgroetsch/fitmodel-rework
optional_path_arguments:
  fit_results_local_path:
  log_local_path:
  raw_sig_map_local_path:
  prev_models_local_path:
optional_fitting_arguments:
  roi_radius: '7.1'
  minimum_point_source_TS: 250
  minimum_morphology_TS_improvement: 16
  minimum_spectral_TS_improvement: 16
  morphology_TS_threshold: 250
  spectrum_TS_threshold: 100
  final_refit_TS_threshold: 100
  minimum_morphology_AIC_improvement: 10
  minimum_spectrum_AIC_improvement: 10
  angular_separation_threshold: 1.0
  point_source_coord_range:
  extended_source_coord_range:
  custom_parameter_boundaries_dict:
  include_old_diffuse_model:
  old_diffuse_model_min_l:
  old_diffuse_model_max_l:
  old_diffuse_model_sigma_b:
  include_hermes_diffuse_model:
  hermes_template_path:
  free_diffuse_norm:
  roi_template_path:
  compute_optional_TS:
  compute_optional_uncertainties:
  use_fast_TS_estimate:
  max_param_retries: 3
pipeline_control_arguments:
  logging_level:
  start_from_raw_map:
  start_from_existing_yml_file_model:
  yml_file_model_path:
  start_from_existing_model_file_model:
  model_file_model_path:
  start_from_existing_fits_file_model:
  fits_file_model_path:
  trusted_source_list:
  trust_all_alterante_morphologies:
  trust_all_alternate_spectra:
  perform_point_source_adding_phase:
  perform_morpholgy_testing_phase:
  alternate_morpholgy_model_list: [Gaussian_on_sphere]
  perform_spectrum_testing_phase:
  alternate_spectrum_model_list: [Log_parabola]
  perform_final_fitting_phase:
  use_parallel_alt_fitting:
map_making_control_arguments:
  make_raw_data_map:
  make_model_map: 'False'
  make_optional_residual_map: 'False'
  plot_size_coord_1:
  plot_size_coord_2:



